const {
  AbsoluteFill,
  OffthreadVideo,
  Audio,
  staticFile,
  Sequence,
  useCurrentFrame,
  interpolate,
  spring,
  useVideoConfig,
} = require('remotion');

// timing.js is generated by generate-voiceover.js
// Falls back to estimated timing if not yet generated
let STEP_TIMING;
try {
  STEP_TIMING = require('./timing').STEP_TIMING;
} catch {
  // Estimated fallback — replace by running generate-voiceover.js
  STEP_TIMING = [
    { id: '01-welcome',          label: 'Welcome',             startFrame:    0, endFrame:  240, audioEndFrame:  230 },
    { id: '03-configure',        label: 'Configure Demo',      startFrame:  240, endFrame:  540, audioEndFrame:  525 },
    { id: '07a-signup',          label: 'Sign Up',             startFrame:  540, endFrame:  780, audioEndFrame:  765 },
    { id: '07b-personal-info',   label: 'Personal Info',       startFrame:  780, endFrame: 1140, audioEndFrame: 1120 },
    { id: '07c-sms',             label: 'SMS Confirmation',    startFrame: 1140, endFrame: 1380, audioEndFrame: 1360 },
    { id: '07d-account-created', label: 'Account Created',     startFrame: 1380, endFrame: 1680, audioEndFrame: 1660 },
    { id: '08-backend-data',     label: 'Backend API',         startFrame: 1680, endFrame: 2040, audioEndFrame: 2020 },
    { id: '09a-dashboard',       label: 'Trust Index · 94',    startFrame: 2040, endFrame: 2490, audioEndFrame: 2465 },
    { id: '09b-linked-accounts', label: 'Linked Accounts',     startFrame: 2490, endFrame: 2730, audioEndFrame: 2710 },
    { id: '09c-data-source',     label: 'Data Source Verified',startFrame: 2730, endFrame: 3090, audioEndFrame: 3065 },
    { id: '09d-watchlist',       label: 'Watchlist · Clear',   startFrame: 3090, endFrame: 3330, audioEndFrame: 3310 },
    { id: '09e-risk-check',      label: 'Risk Check',          startFrame: 3330, endFrame: 3690, audioEndFrame: 3665 },
    { id: '09f-behavior',        label: 'Behavior · Clear',    startFrame: 3690, endFrame: 3930, audioEndFrame: 3910 },
    { id: '11-all-set',          label: 'Verified',            startFrame: 3930, endFrame: 4230, audioEndFrame: 4210 },
    { id: '12-cta',              label: 'Book a Meeting',      startFrame: 4230, endFrame: 4590, audioEndFrame: 4565 },
  ];
}

// ── Design tokens ─────────────────────────────────────────────────────────────
const PLAID_BLACK  = '#0d1117';
const PLAID_WHITE  = '#ffffff';
const PLAID_TEAL   = '#00A67E';
const PLAID_BLUE   = '#1D4ED8';
const FONT_STACK   = 'system-ui, -apple-system, "Helvetica Neue", Arial, sans-serif';

// ── Reusable fade helper ──────────────────────────────────────────────────────
function useFade(frame, inStart, inEnd, outStart, outEnd) {
  return interpolate(
    frame,
    [inStart, inEnd, outStart, outEnd],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );
}

// ── Intro Title Card ──────────────────────────────────────────────────────────
function IntroCard({ frame }) {
  const opacity = useFade(frame, 0, 20, 65, 85);
  const y = interpolate(frame, [0, 20], [30, 0], { extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill
      style={{
        background: `linear-gradient(135deg, ${PLAID_BLACK} 0%, #0a2540 100%)`,
        justifyContent: 'center',
        alignItems: 'center',
        opacity,
      }}
    >
      <div style={{ textAlign: 'center', transform: `translateY(${y}px)` }}>
        {/* Plaid wordmark */}
        <div style={{
          color: PLAID_TEAL,
          fontFamily: FONT_STACK,
          fontWeight: 700,
          fontSize: 22,
          letterSpacing: 6,
          textTransform: 'uppercase',
          marginBottom: 20,
          opacity: 0.9,
        }}>
          PLAID
        </div>
        <div style={{
          color: PLAID_WHITE,
          fontFamily: FONT_STACK,
          fontWeight: 700,
          fontSize: 68,
          lineHeight: 1.1,
          marginBottom: 16,
        }}>
          Identity Verification
        </div>
        <div style={{
          color: 'rgba(255,255,255,0.55)',
          fontFamily: FONT_STACK,
          fontWeight: 400,
          fontSize: 26,
        }}>
          KYC · Fraud Prevention · Compliance
        </div>
      </div>
    </AbsoluteFill>
  );
}

// ── Step Label (lower-third) ──────────────────────────────────────────────────
function StepLabel({ label, frame, relFrame, durationFrames }) {
  const opacity = useFade(relFrame, 0, 12, durationFrames - 15, durationFrames - 3);
  const x = interpolate(relFrame, [0, 12], [-20, 0], { extrapolateRight: 'clamp' });

  return (
    <div style={{
      position: 'absolute',
      bottom: 36,
      left: 48,
      opacity,
      transform: `translateX(${x}px)`,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      pointerEvents: 'none',
    }}>
      <div style={{
        width: 4,
        height: 28,
        background: PLAID_TEAL,
        borderRadius: 2,
      }} />
      <div style={{
        background: 'rgba(0,0,0,0.72)',
        backdropFilter: 'blur(8px)',
        color: PLAID_WHITE,
        fontFamily: FONT_STACK,
        fontWeight: 600,
        fontSize: 17,
        padding: '7px 16px',
        borderRadius: 8,
        letterSpacing: 0.3,
      }}>
        {label}
      </div>
    </div>
  );
}

// ── Trust Index Badge (step 09a) ──────────────────────────────────────────────
function TrustIndexBadge({ frame, relFrame, durationFrames }) {
  const { fps } = useVideoConfig();
  const opacity = useFade(relFrame, 0, 18, durationFrames - 20, durationFrames - 5);

  const scale = spring({
    frame: relFrame,
    fps,
    config: { damping: 14, stiffness: 120, mass: 0.8 },
  });

  return (
    <div style={{
      position: 'absolute',
      top: '12%',
      right: '5%',
      opacity,
      transform: `scale(${scale})`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 6,
      pointerEvents: 'none',
    }}>
      {/* Score ring */}
      <div style={{
        width: 110,
        height: 110,
        borderRadius: '50%',
        border: `5px solid ${PLAID_TEAL}`,
        background: 'rgba(0,166,126,0.12)',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        boxShadow: `0 0 28px rgba(0,166,126,0.45)`,
      }}>
        <div style={{
          color: PLAID_TEAL,
          fontFamily: FONT_STACK,
          fontWeight: 800,
          fontSize: 38,
          lineHeight: 1,
        }}>94</div>
        <div style={{
          color: 'rgba(255,255,255,0.7)',
          fontFamily: FONT_STACK,
          fontWeight: 500,
          fontSize: 11,
          letterSpacing: 1,
          textTransform: 'uppercase',
          marginTop: 2,
        }}>Trust Index</div>
      </div>
      {/* Low risk pill */}
      <div style={{
        background: 'rgba(0,166,126,0.9)',
        color: PLAID_WHITE,
        fontFamily: FONT_STACK,
        fontWeight: 700,
        fontSize: 12,
        padding: '4px 12px',
        borderRadius: 20,
        letterSpacing: 0.5,
        textTransform: 'uppercase',
      }}>
        Low Risk
      </div>
    </div>
  );
}

// ── Match Confirmed callout (step 09c) ────────────────────────────────────────
function MatchCallout({ relFrame, durationFrames }) {
  const opacity = useFade(relFrame, 0, 15, durationFrames - 18, durationFrames - 5);
  const y = interpolate(relFrame, [0, 15], [12, 0], { extrapolateRight: 'clamp' });

  const fields = ['Name', 'Date of Birth', 'Address', 'Phone Number', 'Tax ID'];

  return (
    <div style={{
      position: 'absolute',
      top: '18%',
      right: '4%',
      opacity,
      transform: `translateY(${y}px)`,
      background: 'rgba(10,18,23,0.88)',
      border: `1.5px solid rgba(0,166,126,0.45)`,
      backdropFilter: 'blur(10px)',
      borderRadius: 12,
      padding: '14px 20px',
      pointerEvents: 'none',
    }}>
      <div style={{
        color: PLAID_TEAL,
        fontFamily: FONT_STACK,
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 1,
        textTransform: 'uppercase',
        marginBottom: 10,
      }}>
        All Fields Verified
      </div>
      {fields.map(f => (
        <div key={f} style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          marginBottom: 6,
        }}>
          <div style={{
            width: 18,
            height: 18,
            borderRadius: '50%',
            background: PLAID_TEAL,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            fontSize: 11,
            color: PLAID_WHITE,
            fontWeight: 700,
            flexShrink: 0,
          }}>✓</div>
          <span style={{
            color: PLAID_WHITE,
            fontFamily: FONT_STACK,
            fontSize: 14,
            fontWeight: 500,
          }}>{f}</span>
          <span style={{
            color: PLAID_TEAL,
            fontFamily: FONT_STACK,
            fontSize: 12,
            fontWeight: 600,
            marginLeft: 'auto',
            paddingLeft: 12,
          }}>match</span>
        </div>
      ))}
    </div>
  );
}

// ── Watchlist Clear badge (step 09d) ─────────────────────────────────────────
function WatchlistBadge({ relFrame, durationFrames }) {
  const opacity = useFade(relFrame, 0, 15, durationFrames - 18, durationFrames - 5);
  const scale = interpolate(relFrame, [0, 15], [0.88, 1], { extrapolateRight: 'clamp' });

  return (
    <div style={{
      position: 'absolute',
      top: '20%',
      right: '5%',
      opacity,
      transform: `scale(${scale})`,
      background: 'rgba(0,166,126,0.12)',
      border: `2px solid ${PLAID_TEAL}`,
      borderRadius: 14,
      padding: '16px 24px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: 8,
      pointerEvents: 'none',
    }}>
      <div style={{ fontSize: 36 }}>🛡️</div>
      <div style={{
        color: PLAID_TEAL,
        fontFamily: FONT_STACK,
        fontWeight: 700,
        fontSize: 15,
        textAlign: 'center',
      }}>Watchlist Screening</div>
      <div style={{
        color: PLAID_WHITE,
        fontFamily: FONT_STACK,
        fontWeight: 600,
        fontSize: 20,
      }}>Clear</div>
      <div style={{
        color: 'rgba(255,255,255,0.55)',
        fontFamily: FONT_STACK,
        fontSize: 11,
        textAlign: 'center',
        maxWidth: 140,
        lineHeight: 1.4,
      }}>AML · PEP · Sanctions</div>
    </div>
  );
}

// ── Risk Summary callout (step 09e) ──────────────────────────────────────────
function RiskCallout({ relFrame, durationFrames }) {
  const opacity = useFade(relFrame, 0, 15, durationFrames - 18, durationFrames - 5);

  const signals = [
    { label: 'Device Risk',      score: 0,  level: 'Low' },
    { label: 'Phone Risk',       score: 0,  level: 'Low' },
    { label: 'Network Risk',     score: 0,  level: 'Low' },
    { label: 'Email Risk',       score: 22, level: 'Low' },
    { label: 'Behavior',         score: null, level: 'Neutral' },
  ];

  return (
    <div style={{
      position: 'absolute',
      top: '15%',
      right: '4%',
      opacity,
      background: 'rgba(10,18,23,0.9)',
      border: '1.5px solid rgba(255,255,255,0.12)',
      backdropFilter: 'blur(10px)',
      borderRadius: 12,
      padding: '14px 18px',
      minWidth: 200,
      pointerEvents: 'none',
    }}>
      <div style={{
        color: PLAID_WHITE,
        fontFamily: FONT_STACK,
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
        marginBottom: 12,
        opacity: 0.7,
      }}>Risk Signals</div>
      {signals.map(s => (
        <div key={s.label} style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 8,
          gap: 16,
        }}>
          <span style={{ color: 'rgba(255,255,255,0.7)', fontFamily: FONT_STACK, fontSize: 13 }}>
            {s.label}
          </span>
          <span style={{
            color: s.level === 'Low' || s.level === 'Neutral' ? PLAID_TEAL : '#f87171',
            fontFamily: FONT_STACK,
            fontSize: 13,
            fontWeight: 600,
          }}>
            {s.level}
          </span>
        </div>
      ))}
    </div>
  );
}

// ── Outro CTA Card ────────────────────────────────────────────────────────────
function OutroCard({ frame, relFrame, durationFrames }) {
  const opacity = useFade(relFrame, 0, 20, durationFrames - 20, durationFrames);
  const y = interpolate(relFrame, [0, 20], [20, 0], { extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill style={{
      background: `linear-gradient(135deg, #0a2540 0%, #0d3b2e 100%)`,
      justifyContent: 'center',
      alignItems: 'center',
      opacity,
    }}>
      <div style={{ textAlign: 'center', transform: `translateY(${y}px)`, padding: '0 80px' }}>
        <div style={{
          color: PLAID_TEAL,
          fontFamily: FONT_STACK,
          fontWeight: 700,
          fontSize: 16,
          letterSpacing: 5,
          textTransform: 'uppercase',
          marginBottom: 24,
        }}>PLAID · IDENTITY VERIFICATION</div>
        <div style={{
          color: PLAID_WHITE,
          fontFamily: FONT_STACK,
          fontWeight: 700,
          fontSize: 52,
          lineHeight: 1.15,
          marginBottom: 20,
        }}>
          Ready to get started?
        </div>
        <div style={{
          color: 'rgba(255,255,255,0.65)',
          fontFamily: FONT_STACK,
          fontSize: 22,
          lineHeight: 1.5,
          marginBottom: 40,
          maxWidth: 680,
          margin: '0 auto 40px',
        }}>
          Reduce fraud, accelerate onboarding, and stay KYC compliant — at scale.
        </div>
        <div style={{
          display: 'inline-block',
          background: PLAID_TEAL,
          color: PLAID_WHITE,
          fontFamily: FONT_STACK,
          fontWeight: 700,
          fontSize: 20,
          padding: '16px 44px',
          borderRadius: 50,
          letterSpacing: 0.5,
        }}>
          Book a Meeting
        </div>
        <div style={{
          color: 'rgba(255,255,255,0.35)',
          fontFamily: FONT_STACK,
          fontSize: 14,
          marginTop: 32,
        }}>
          plaid.com/identity-verification
        </div>
      </div>
    </AbsoluteFill>
  );
}

// ── Plaid watermark ────────────────────────────────────────────────────────────
function PlaidWatermark() {
  return (
    <div style={{
      position: 'absolute',
      top: 22,
      right: 28,
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      pointerEvents: 'none',
    }}>
      <div style={{
        background: PLAID_TEAL,
        width: 8,
        height: 8,
        borderRadius: '50%',
      }} />
      <span style={{
        color: 'rgba(255,255,255,0.5)',
        fontFamily: FONT_STACK,
        fontWeight: 700,
        fontSize: 13,
        letterSpacing: 2,
        textTransform: 'uppercase',
      }}>Plaid</span>
    </div>
  );
}

// ── Main composition ──────────────────────────────────────────────────────────
const DemoComposition = () => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();

  const INTRO_DURATION = 90;  // 3s intro card
  const OUTRO_START    = STEP_TIMING[STEP_TIMING.length - 1]?.startFrame ?? (durationInFrames - 180);
  const OUTRO_DURATION = durationInFrames - OUTRO_START;

  // Find which step we're currently in (for step labels + overlays)
  const currentStep = STEP_TIMING.find(
    s => frame >= s.startFrame && frame < (s.endFrame ?? durationInFrames)
  );

  // Video fade-in from black
  const videoOpacity = interpolate(frame, [0, 15], [0, 1], { extrapolateRight: 'clamp' });
  // Video fade-out to outro
  const videoFadeOut = interpolate(frame, [OUTRO_START - 20, OUTRO_START], [1, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });
  const videoVis = Math.min(videoOpacity, videoFadeOut);

  return (
    <AbsoluteFill style={{ background: PLAID_BLACK, overflow: 'hidden' }}>

      {/* ── Base video ── */}
      <AbsoluteFill style={{ opacity: videoVis }}>
        <OffthreadVideo
          src={staticFile('recording.webm')}
          style={{ width: '100%', height: '100%', objectFit: 'contain' }}
          volume={0}
        />
      </AbsoluteFill>

      {/* ── Voiceover audio (full track, synced to video) ── */}
      <Audio src={staticFile('voiceover.mp3')} volume={1} />

      {/* ── Intro title card (first 3s) ── */}
      {frame < INTRO_DURATION && (
        <IntroCard frame={frame} />
      )}

      {/* ── Plaid watermark (visible after intro, before outro) ── */}
      {frame >= INTRO_DURATION && frame < OUTRO_START && (
        <PlaidWatermark />
      )}

      {/* ── Step label lower-thirds ── */}
      {currentStep && frame >= INTRO_DURATION && frame < OUTRO_START && (
        <Sequence from={currentStep.startFrame} durationInFrames={currentStep.endFrame - currentStep.startFrame}>
          <StepLabel
            label={currentStep.label}
            frame={frame}
            relFrame={frame - currentStep.startFrame}
            durationFrames={currentStep.endFrame - currentStep.startFrame}
          />
        </Sequence>
      )}

      {/* ── Trust Index Badge — step 09a ── */}
      {(() => {
        const s = STEP_TIMING.find(x => x.id === '09a-dashboard');
        if (!s || frame < s.startFrame || frame >= s.endFrame) return null;
        const rel = frame - s.startFrame;
        const dur = s.endFrame - s.startFrame;
        return <TrustIndexBadge frame={frame} relFrame={rel} durationFrames={dur} />;
      })()}

      {/* ── Match Callout — step 09c ── */}
      {(() => {
        const s = STEP_TIMING.find(x => x.id === '09c-data-source');
        if (!s || frame < s.startFrame || frame >= s.endFrame) return null;
        const rel = frame - s.startFrame;
        const dur = s.endFrame - s.startFrame;
        return <MatchCallout relFrame={rel} durationFrames={dur} />;
      })()}

      {/* ── Watchlist Badge — step 09d ── */}
      {(() => {
        const s = STEP_TIMING.find(x => x.id === '09d-watchlist');
        if (!s || frame < s.startFrame || frame >= s.endFrame) return null;
        const rel = frame - s.startFrame;
        const dur = s.endFrame - s.startFrame;
        return <WatchlistBadge relFrame={rel} durationFrames={dur} />;
      })()}

      {/* ── Risk Callout — step 09e ── */}
      {(() => {
        const s = STEP_TIMING.find(x => x.id === '09e-risk-check');
        if (!s || frame < s.startFrame || frame >= s.endFrame) return null;
        const rel = frame - s.startFrame;
        const dur = s.endFrame - s.startFrame;
        return <RiskCallout relFrame={rel} durationFrames={dur} />;
      })()}

      {/* ── Outro CTA card (last step) ── */}
      {frame >= OUTRO_START && (
        <OutroCard
          frame={frame}
          relFrame={frame - OUTRO_START}
          durationFrames={OUTRO_DURATION}
        />
      )}

    </AbsoluteFill>
  );
};

module.exports = { DemoComposition };
