// Auto-generated by generate-voiceover.js — do not edit manually
// Re-run: node scripts/generate-voiceover.js

const STEP_TIMING = [
  {
    "id": "portfolio-dashboard",
    "label": "My Portfolio dashboard",
    "startFrame": 0,
    "endFrame": 357,
    "audioEndFrame": 327
  },
  {
    "id": "transfer-method-choice",
    "label": "Manual vs Plaid choice",
    "startFrame": 357,
    "endFrame": 736,
    "audioEndFrame": 706
  },
  {
    "id": "plaid-link-launch",
    "label": "Plaid Link",
    "startFrame": 736,
    "endFrame": 1265,
    "audioEndFrame": 1042
  },
  {
    "id": "connecting-status",
    "label": "Retrieving account details",
    "startFrame": 1265,
    "endFrame": 1380,
    "audioEndFrame": 1582
  },
  {
    "id": "holdings-full-transfer",
    "label": "Holdings staging — full transfer",
    "startFrame": 1380,
    "endFrame": 2118,
    "audioEndFrame": 1841
  },
  {
    "id": "holdings-partial-transfer",
    "label": "Partial transfer selection",
    "startFrame": 2118,
    "endFrame": 2516,
    "audioEndFrame": 2479
  },
  {
    "id": "acats-form-prefilled",
    "label": "ACATS form pre-filled",
    "startFrame": 2516,
    "endFrame": 2570,
    "audioEndFrame": 2863
  },
  {
    "id": "submitting-request",
    "label": "Submitting to DTCC",
    "startFrame": 2570,
    "endFrame": 3239,
    "audioEndFrame": 2880
  },
  {
    "id": "transfer-confirmed",
    "label": "Transfer confirmed",
    "startFrame": 3239,
    "endFrame": 3550,
    "audioEndFrame": 3520
  }
];

module.exports = { STEP_TIMING };
