// Auto-generated by generate-voiceover.js — do not edit manually
// Re-run: node scripts/generate-voiceover.js

const STEP_TIMING = [
  {
    "id": "layer-session",
    "label": "Plaid Layer session",
    "startFrame": 0,
    "endFrame": 3302,
    "audioEndFrame": 405
  },
  {
    "id": "generating-report",
    "label": "Generating the Consumer Report",
    "startFrame": 3302,
    "endFrame": 3719,
    "audioEndFrame": 3659
  },
  {
    "id": "income-insights-reveal",
    "label": "CRA Income Insights",
    "startFrame": 3719,
    "endFrame": 4275,
    "audioEndFrame": 4215
  },
  {
    "id": "income-insights-slide",
    "label": "Verified income beat",
    "startFrame": 4275,
    "endFrame": 4681,
    "audioEndFrame": 4621
  },
  {
    "id": "cashflow-insights-reveal",
    "label": "CRA Cash Flow Insights",
    "startFrame": 4681,
    "endFrame": 5196,
    "audioEndFrame": 5136
  },
  {
    "id": "cashflow-insights-slide",
    "label": "Ability-to-pay attributes",
    "startFrame": 5196,
    "endFrame": 5610,
    "audioEndFrame": 5550
  },
  {
    "id": "loan-approved",
    "label": "Approved",
    "startFrame": 5610,
    "endFrame": 6031,
    "audioEndFrame": 5956
  },
  {
    "id": "value-summary-slide",
    "label": "Value Summary",
    "startFrame": 6031,
    "endFrame": 6121,
    "audioEndFrame": 6429
  }
];

module.exports = { STEP_TIMING };
